allowBuilds:
  simple-git-hooks: true

autoInstallPeers: false

color: always

engineStrict: true

minimumReleaseAgeExclude:
  - '@standard-config/*'

overrides:
  '@prettier/plugin-oxc': '-'

strictPeerDependencies: true

trustPolicy: no-downgrade
